name = "chatbot-openrouter"
main = "src/index.ts"
compatibility_date = "2023-12-31"

[dev]
  port = 8787
  ip = "0.0.0.0"
  local_protocol = "http"

[[d1_databases]]
binding = "DB"
database_name = "chatbot-openrouter-db"
database_id = "9dc4a4ae-3ab0-459a-aa42-ca3ad2427d8f"

[vars]
NODE_ENV = "development"
database_id = "9dc4a4ae-3ab0-459a-aa42-ca3ad2427d8f"